name: WarpCore
main: RoMo\WarpCore\WarpCore
author: RoMo_Official
version: 3.1.3
api:
  - 5.0.0

permissions:
  warpcore.manage.warp:
    default: op
  warpcore.use.warp:
    default: true

depend:
  - StarGate-Atlantis

softdepend:
  - SqlCore

virions:
  - SOF3/await-generator/master
  - drirainMCBE/translator/master
  - poggit/libasynql/master